const IMAGE_MAP: Record<string, string> = {
  'angus beef barley': '/images/angus_beef_barley_soup.png',
  'beef barley': '/images/angus_beef_barley_soup.png',
  'beef mushroom barley': '/images/mushroom_barley_soup.png',
  'broccoli cheddar': '/images/broccoli_cheddar_soup.png',
  'butternut squash': '/images/butternut_squash_soup.png',
  'french onion': '/images/french_onion_soup.png',
  'tomato basil': '/images/creamy_tomato_basil_soup.png',
  'creamy tomato': '/images/creamy_tomato_basil_soup.png',
  'garden minestrone': '/images/garden_minestrone_soup.png',
  'minestrone': '/images/garden_minestrone_soup.png',
  'italian wedding': '/images/italian_wedding_soup.png',
  'clam chowder': '/images/clam_chowder_soup.png',
  'new england clam': '/images/clam_chowder_soup.png',
  'manhattan clam': '/images/clam_chowder_soup.png',
  'chicken pot pie': '/images/chicken_pot_pie_soup.png',
  'seafood bisque': '/images/seafood_bisque_soup.png',
  'split pea': '/images/split_pea_soup.png',
  'green pea': '/images/split_pea_soup.png',
  'mushroom barley': '/images/mushroom_barley_soup.png',
  'potato bacon': '/images/potato_bacon_soup.png',
  'potato cheddar': '/images/loaded_baked_potato_soup.png',
  'lentil': '/images/lentil_soup.png',
  'lucky lentil': '/images/lentil_soup.png',
  'gazpacho': '/images/gazpacho_cold_soup.png',
  'buffalo chicken': '/images/buffalo_chicken_soup.png',
  'carrot ginger': '/images/carrot_ginger_soup.png',
  'creamy mushroom': '/images/creamy_mushroom_soup.png',
  'mushroom bisque': '/images/creamy_mushroom_soup.png',
  'white chilli': '/images/white_chili_turkey_soup.png',
  'white chili': '/images/white_chili_turkey_soup.png',
  'tomato bisque': '/images/tomato_bisque_soup.png',
  'chicken florentine': '/images/chicken_florentine_soup.png',
  'black bean': '/images/black_bean_soup.png',
  'santa fe': '/images/black_bean_soup.png',
  'southwest black': '/images/black_bean_soup.png',
  'vegetable soup': '/images/vegetable_soup.png',
  'beef vegetable': '/images/vegetable_soup.png',
  'summer vegetable': '/images/vegetable_soup.png',
  'roasted red pepper': '/images/roasted_red_pepper_bisque.png',
  'chickpea': '/images/chickpea_soup.png',
  'pasta fagioli': '/images/pasta_fagioli_soup.png',
  'corn chowder': '/images/corn_chowder_soup.png',
  'creamy corn': '/images/corn_soup_creamy.png',
  'beef stew': '/images/beef_stew_soup.png',
  'chicken orzo': '/images/chicken_orzo_soup.png',
  'lemon chicken orzo': '/images/chicken_orzo_soup.png',
  'chicken lime orzo': '/images/chicken_orzo_soup.png',
  'chicken noodle': '/images/chicken_noodle_soup.png',
  'chicken tortellini': '/images/chicken_tortellini_soup.png',
  'ham bean': '/images/ham_bean_soup.png',
  'potato leek': '/images/potato_leek_soup.png',
  'cauliflower': '/images/cauliflower_soup.png',
  'broccoli cauliflower': '/images/cauliflower_soup.png',
  'curried chicken': '/images/curried_chicken_soup.png',
  'hot and sour': '/images/hot_and_sour_soup.png',
  'crab bisque': '/images/crab_bisque_soup.png',
  'tortilla soup': '/images/tortilla_soup.png',
  'wonton': '/images/wonton_soup.png',
  'matzo ball': '/images/matzo_ball_soup.png',
  'asparagus': '/images/cream_of_asparagus_soup.png',
  'sweet potato': '/images/sweet_potato_soup.png',
  'vegetarian chili': '/images/vegetarian_chili_soup.png',
  'chicken gumbo': '/images/chicken_gumbo_soup.png',
  'cabbage soup': '/images/cabbage_soup_hearty.png',
  'coconut curry': '/images/coconut_curry_soup.png',
  'pho': '/images/pho_vietnamese_soup.png',
  'ramen': '/images/ramen_noodle_soup.png',
  'avgolemono': '/images/avgolemono_greek_soup.png',
  'borscht': '/images/borscht_beet_soup.png',
  'mulligatawny': '/images/mulligatawny_soup.png',
  'pozole': '/images/pozole_mexican_soup.png',
  'cioppino': '/images/cioppino_seafood_stew.png',
  'bouillabaisse': '/images/bouillabaisse_fish_stew.png',
  'beef chili': '/images/bowl_of_beef_chili.png',
  'beef chilli': '/images/bowl_of_beef_chili.png',
  'angus beef chilli': '/images/bowl_of_beef_chili.png',
  'spinach orzo': '/images/spinach_soup_creamy.png',
  'creamy rice spinach': '/images/spinach_soup_creamy.png',
  'carrot bisque': '/images/carrot_ginger_soup.png',
  'creamy carrots': '/images/carrot_ginger_soup.png',
  'chunky celery': '/images/celery_soup_cream.png',
  'celery': '/images/celery_soup_cream.png',
  'rustic tomato': '/images/tomato_bisque_soup.png',
  'tomato soup': '/images/tomato_bisque_soup.png',
  'wild rice': '/images/mushroom_risotto_entree.png',
  'pumpkin': '/images/pumpkin_soup_fall.png',
  'onion soup': '/images/onion_soup_simple.png',
  'zucchini': '/images/zucchini_soup_light.png',
  'sausage kale': '/images/sausage_kale_soup.png',
  'kidney bean': '/images/black_bean_soup.png',
  'whitebeans': '/images/ham_bean_soup.png',
  'smoked ham': '/images/ham_bean_soup.png',
  'chicken rice': '/images/chicken_fried_rice.png',
  'creamy chicken': '/images/chicken_pot_pie_soup.png',
  'chicken spinach': '/images/chicken_florentine_soup.png',
  'vegetable bisque': '/images/vegetable_soup.png',
  
  'cuban': '/images/cuban_panini_sandwich.png',
  'meatball parmesan': '/images/meatball_parmesan_panini.png',
  'meatball': '/images/meatball_parmesan_panini.png',
  'turkey cranberry': '/images/turkey_cranberry_panini.png',
  'reuben': '/images/reuben_panini.png',
  'corn beef': '/images/reuben_panini.png',
  'pastrami': '/images/reuben_panini.png',
  'buffalo chicken panini': '/images/buffalo_chicken_panini.png',
  'buffalo chicken cutlet': '/images/buffalo_chicken_panini.png',
  'tuna melt': '/images/tuna_melt_panini.png',
  'turkey club': '/images/turkey_club_sandwich.png',
  'blt': '/images/blt_sandwich.png',
  'chicken wrap': '/images/chicken_wrap_sandwich.png',
  'egg salad': '/images/egg_salad_sandwich.png',
  'chicken caesar': '/images/chicken_caesar_wrap.png',
  'roast beef': '/images/roast_beef_sandwich.png',
  'chicken salad': '/images/chicken_salad_sandwich.png',
  'curried chicken salad': '/images/chicken_salad_sandwich.png',
  'ham cheese': '/images/ham_and_cheese_sandwich.png',
  'ham swiss': '/images/ham_and_cheese_sandwich.png',
  'ham honey': '/images/ham_and_cheese_sandwich.png',
  'ham mozzarella': '/images/ham_and_cheese_sandwich.png',
  'italian': '/images/italian_sub_sandwich.png',
  'philly': '/images/philly_cheesesteak_sandwich.png',
  'cheesesteak': '/images/philly_cheesesteak_sandwich.png',
  'veggie wrap': '/images/veggie_wrap.png',
  'vegetable wrap': '/images/veggie_wrap.png',
  'southwest chicken': '/images/southwest_chicken_wrap.png',
  'asian': '/images/asian_sesame_salad.png',
  'tuna salad': '/images/tuna_salad_sandwich.png',
  'lobster': '/images/lobster_roll_sandwich.png',
  'smoked turkey': '/images/smoked_turkey_panini.png',
  'turkey bacon': '/images/turkey_bacon_panini.png',
  'veggie panini': '/images/veggie_panini.png',
  'bacon avocado': '/images/bacon_avocado_turkey_sandwich.png',
  'pulled pork': '/images/pulled_pork_sandwich.png',
  'bbq pulled': '/images/pulled_pork_sandwich.png',
  'chicken cutlet': '/images/chicken_cutlet_sandwich.png',
  'sloppy joe': '/images/sloppy_joe_sandwich.png',
  'monte cristo': '/images/monte_cristo_sandwich.png',
  'gyro': '/images/gyro_wrap.png',
  'falafel': '/images/falafel_wrap.png',
  'crab cake': '/images/crab_cake_sandwich.png',
  'caprese': '/images/caprese_panini.png',
  'grilled cheese': '/images/grilled_cheese_sandwich.png',
  'bbq chicken': '/images/bbq_chicken_panini.png',
  'bbq bacon': '/images/bbq_chicken_panini.png',
  'portobello': '/images/portobello_mushroom_panini.png',
  'chicken pesto': '/images/chicken_pesto_panini.png',
  'pesto mayo': '/images/chicken_pesto_panini.png',
  'steak panini': '/images/steak_panini.png',
  'grilled chicken': '/images/bbq_chicken_panini.png',
  
  'caesar salad': '/images/caesar_salad.png',
  'greek salad': '/images/greek_salad.png',
  'cobb salad': '/images/cobb_salad.png',
  'garden salad': '/images/garden_salad.png',
  'caprese salad': '/images/caprese_salad.png',
  'spinach salad': '/images/spinach_salad.png',
  'asian sesame': '/images/asian_sesame_salad.png',
  'grilled chicken salad': '/images/grilled_chicken_salad.png',
  'avocado salad': '/images/avocado_salad.png',
  'kale salad': '/images/kale_salad.png',
  'quinoa salad': '/images/quinoa_salad.png',
  'taco salad': '/images/taco_salad.png',
  'waldorf': '/images/waldorf_salad.png',
  'nicoise': '/images/nicoise_salad.png',
  'antipasto': '/images/antipasto_salad.png',
  'beet salad': '/images/beet_salad.png',
  
  'pasta primavera': '/images/pasta_primavera_entree.png',
  'chicken parmesan': '/images/chicken_parmesan_entree.png',
  'chicken parm': '/images/chicken_parmesan_entree.png',
  'lasagna': '/images/lasagna_entree.png',
  'beef stroganoff': '/images/beef_stroganoff_entree.png',
  'shrimp scampi': '/images/shrimp_scampi_entree.png',
  'salmon': '/images/salmon_fillet_entree.png',
  'eggplant parmesan': '/images/eggplant_parmesan_entree.png',
  'eggplant parm': '/images/eggplant_parmesan_entree.png',
  'stuffed pepper': '/images/stuffed_peppers_entree.png',
  'chicken marsala': '/images/chicken_marsala_entree.png',
  'meatloaf': '/images/meatloaf_entree.png',
  'chicken alfredo': '/images/chicken_alfredo_entree.png',
  'pot roast': '/images/pot_roast_entree.png',
  'mac and cheese': '/images/mac_and_cheese_entree.png',
  'mac cheese': '/images/mac_and_cheese_entree.png',
  'shepherd pie': '/images/shepherd\'s_pie_entree.png',
  'shepherds pie': '/images/shepherd\'s_pie_entree.png',
  'penne vodka': '/images/penne_vodka_entree.png',
  'baked ziti': '/images/baked_ziti_entree.png',
  'chicken francese': '/images/chicken_francese_entree.png',
  'veal piccata': '/images/veal_piccata_entree.png',
  'spaghetti meatball': '/images/spaghetti_and_meatballs.png',
  'rigatoni bolognese': '/images/rigatoni_bolognese_entree.png',
  'stir fry': '/images/stir_fry_vegetables_entree.png',
  'teriyaki chicken': '/images/teriyaki_chicken_entree.png',
  'roasted chicken': '/images/roasted_chicken_entree.png',
  'herb roasted': '/images/roasted_chicken_entree.png',
  'fish and chips': '/images/fish_and_chips_entree.png',
  'fish chips': '/images/fish_and_chips_entree.png',
  'tilapia': '/images/grilled_tilapia_entree.png',
  'bbq ribs': '/images/bbq_ribs_entree.png',
  'turkey meatball': '/images/turkey_meatballs_entree.png',
  'fried rice': '/images/chicken_fried_rice.png',
  'vegetable curry': '/images/vegetable_curry_entree.png',
  'mashed potato': '/images/meatloaf_entree.png',
  'chicken cordon': '/images/chicken_cordon_bleu.png',
  'pork tenderloin': '/images/pork_tenderloin_entree.png',
  'mushroom risotto': '/images/mushroom_risotto_entree.png',
  'grilled vegetable': '/images/grilled_vegetable_platter.png',
  'quiche': '/images/quiche_lorraine_entree.png',
  'beef burgundy': '/images/beef_burgundy_stew.png',
  'lobster mac': '/images/lobster_mac_cheese.png',
  'lamb chop': '/images/lamb_chops_entree.png',
  'jambalaya': '/images/jambalaya_rice_dish.png',
  'paella': '/images/paella_spanish_rice.png',
  'tikka masala': '/images/chicken_tikka_masala.png',
  'pad thai': '/images/pad_thai_noodles.png',
  'general tso': '/images/general_tso_chicken.png',
  'orange chicken': '/images/orange_chicken_entree.png',
  'sweet sour': '/images/sweet_and_sour_chicken.png',
  'lo mein': '/images/beef_lo_mein_noodles.png',
  'kung pao': '/images/kung_pao_chicken.png',
  'mongolian beef': '/images/mongolian_beef_entree.png',
  'sesame chicken': '/images/sesame_chicken_entree.png',
  'biryani': '/images/chicken_biryani_rice.png',
  'butter chicken': '/images/butter_chicken_curry.png',
  'shawarma': '/images/lamb_shawarma_wrap.png',
  'souvlaki': '/images/chicken_souvlaki_plate.png',
  'fish taco': '/images/fish_tacos.png',
  'carnitas': '/images/carnitas_tacos.png',
  'beef taco': '/images/beef_tacos.png',
  'burrito bowl': '/images/burrito_bowl.png',
  'enchilada': '/images/enchiladas_plate.png',
  'tamale': '/images/tamales_mexican.png',
  'chile relleno': '/images/chile_relleno.png',
  'fajita': '/images/fajitas_plate.png',
  'empanada': '/images/beef_empanadas.png',
  'arepa': '/images/arepa_sandwich.png',
  'pupusa': '/images/pupusa_plate.png',
  'elote': '/images/elote_mexican_corn.png',
};

export function getImageForItem(itemName: string, itemType?: string): string | undefined {
  const lowerName = itemName.toLowerCase();
  
  for (const [key, imagePath] of Object.entries(IMAGE_MAP)) {
    if (lowerName.includes(key)) {
      return imagePath;
    }
  }
  
  if (itemType) {
    const typeDefaults: Record<string, string> = {
      'soup': '/images/chicken_noodle_soup.png',
      'panini': '/images/bbq_chicken_panini.png',
      'sandwich': '/images/turkey_club_sandwich.png',
      'salad': '/images/garden_salad.png',
      'entree': '/images/chicken_parmesan_entree.png',
    };
    return typeDefaults[itemType];
  }
  
  return undefined;
}
